### PR TITLE
add configurable target path for spec assets

### PR DESCRIPTION
**Pull request by ertrzyiks**
Without custom target path __assetic_havvg_jasmine_specs_js_ replace project root path.

```
$ app/console router:debug
[router] Current routes
Name                                            Method   Scheme Host Path                                                                                     
_assetic_havvg_jasmine_specs_js                 ANY      ANY    ANY  /       
```

### CODE REVIEW

**Comment by karolsojko** [comment]
:+1:

**Comment by sskorc** [comment]
:+1:

**Comment by karolsojko** [comment]
@havvg any chance for having this merged ?

**Comment by karolsojko** [comment]
Thanks a lot :)

**Comment by havvg** [comment]
Sorry for the delay, missed it out :-)

**Pull request merged**
